### ISSUE TITLE
运行bash recon.sh后出现的问题

### ISSUE THREAD

**Issue by zhd861564272** [openxrlab/xrdocument#6] opened 2022-10-17 08:29 UTC
Step 3: Re-extract/match with superpoint
100%|█████████████████████████████████████████| 371/371 [00:40<00:00, 9.22it/s]
Traceback (most recent call last):
File "tools/recon_feature_extract.py", line 58, in <module>
args.extractor)
File "tools/recon_feature_extract.py", line 42, in main
write_features_binary(features, feature_bin_path)
File "/home/zhd/xr/XRARdemo/XRLocalization/tools/recon_read_write_data.py", line 99, in write_features_binary
file.write(struct.pack('<256f', *feature.descriptors[:, j]))
struct.error: pack expected 256 items for packing (got 512)
extract superpoint failed

**Comment by eugenelyj** [comment] 2022-10-24 02:22
@zhd861564272 Hi, did you use D2Net? We fix a related bug, see [XRLocalization](https://github.com/openxrlab/xrlocalization/issues/12).
By the way, We recommend SuperPoint, which provides faster and more accurate performance.

**Comment by zhd861564272** [comment] 2022-10-25 07:33
> @zhd861564272 Hi, did you use D2Net? We fix a related bug, see [XRLocalization](https://github.com/openxrlab/xrlocalization/issues/12). By the way, We recommend SuperPoint, which provides faster and more accurate performance.

**Comment by zhd861564272** [comment] 2022-10-25 07:50
> @zhd861564272 Hi, did you use D2Net? We fix a related bug, see [XRLocalization](https://github.com/openxrlab/xrlocalization/issues/12). By the way, We recommend SuperPoint, which provides faster and more accurate performance.

Hi,thank you for your answer.A new problem occurred when I used the fix file in xrlocalization.Can you give me a hand ?Thank you.
Here is what went wrong.
Step 3: Re-extract/match with superpoint
100%|█████████████████████████████████████████| 540/540 [00:58<00:00,  9.25it/s]

100%|██████████████████████████████████████| 7162/7162 [00:52<00:00, 136.84it/s]
Step 4: Re-triangulate
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
recon.sh：行 56:  8591 已放弃               （核心已转储） ./bin/run_triangulation ${SFM_DIR} ${SFM_DIR}/features.bin ${SFM_DIR}/matching.bin ${REFINE_DIR}
run triangulation failed

**Comment by eugenelyj** [comment] 2022-10-25 07:58
@zhd861564272 Hi, could you provide some details about your environment. For example, what operating system do you use? And if possible, could you send me a link for downloading the data?

**Comment by zhd861564272** [comment] 2022-10-25 08:58
> @zhd861564272 Hi, could you provide some details about your environment. For example, what operating system do you use? And if possible, could you send me a link for downloading the data?

ok,System:Ubuntu 18.04.6 LTS 64-bit;Python 3.7.13;cmake version 3.19.0;
I put the binaries on the Baidu disk:链接：https://pan.baidu.com/s/1xEhnKfnGLHX0ZT96n6bOqQ
提取码：2022
Is there anything else  you need?

**Comment by eugenelyj** [comment] 2022-11-03 08:00
@zhd861564272 Hi, the error came from xrsfm and now it is fixed in https://github.com/openxrlab/xrsfm/pull/8

**Comment by zhd861564272** [comment] 2022-12-02 06:56
No new supported iPhone14pro/pro max.yaml found
directory:"xrslam/xrslam-ios/visualizer/configs/‘’
not found the iPhone14pro/pro max.yaml .Can you add it ? Thankyou

**Comment by eugenelyj** [comment] 2022-12-02 07:12
@zhd861564272 
Unfortunately, current supported devices do not contain iPhone14pro and we do not have a recent plan to support it.
The full list of supported devices can be found in the [page](https://github.com/openxrlab/xrslam/blob/main/docs/en/supported_devices.md).
But you can calibrate your phone with tools like [kalibr](https://github.com/ethz-asl/kalibr) and create your custom config file in yaml format.

**Comment by yl-1993** [comment] 2023-02-26 14:03
Feel free to re-open it if the problem is not solved.

**Closed as completed by yl-1993** 2023-02-26 14:03 UTC
